name: Prettier

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  prettier-check:
    name: Checking Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier Check
        run: |
          npx prettier --check "**/*.{js,ts,tsx,md,json}" || exit 1
